- name: Install Docker
  include_tasks: docker.yml

- name: Clone app from GitHub
  include_tasks: git.yml

- name: Deploy containers
  include_tasks: containers.yml

- name: Verify services are running
  include_tasks: verify.yml
