---
- name: Provision and Deploy YOLO App with Docker
  hosts: all
  become: yes
  vars:
    app_name: yolo-ecommerce
    mongodb_container_name: mongodb
    frontend_container_name: yolo-frontend
    backend_container_name: yolo-backend
  roles:
     - role: docker
     - role: clone
     - role: mongodb
 