---
- name: Pull image from repository
  docker_image:
    name: shikul/leena-yolo-client:v1.0.0
    source: pull

- name: Create Node.js frontend Container
  docker_container:
    name: leena-yolo-client
    image: shikul/leena-yolo-client:v1.0.0
    networks:
      - name: app-net
    ports:
      - "3000:3000"
    command: "npm start"
  become: yes