---
- name: Pull image from repository
  docker_image:
    name: shikul/leena-yolo-client:v1.0.0
    source: pull

- name: Create Node.js Backend Container
  docker_container:
    name: leena-yolo-client
    image: shikul/leena-yolo-client:v1.0.0
    networks:
      - name: app-net
    ports:
      - "5000:5000"
    command: "npm start"
  become: yes