apiVersion: apps/v1
kind: Deployment
metadata:
  name: yolo-app-backend
spec:
  selector:
    matchLabels:
      app: yolo-app-backend
  template:
    metadata:
      labels:
        app: yolo-app-backend
    spec:
      containers:
      - name: yolo-app-backend
        image: shikul/leena-app-backend:v1.1.0
        resources:
          limits:
            memory: "128Mi"
            cpu: "200m"
        ports:
        - name: backend-port
          containerPort: 5000