apiVersion: apps/v1
kind: Deployment
metadata:
  name: yolo-app-frontend
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: yolo-app-frontend
  template:
    metadata:
      labels:
        app: yolo-app-frontend
    spec:
      containers:
      - name: yolo-app-frontend
        image: shikul/leena-yolo-client:v1.0.0
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "100m"
            memory: "128Mi"