apiVersion: apps/v1
kind: Deployment
metadata:
  name: yolo-app-frontend
spec:
  selector:
    matchLabels:
      app: yolo-app-frontend
  template:
    metadata:
      labels:
        app: yolo-app-frontend
    spec:
      containers:
      - name: yolo-app-frontend
        image: shikul/leena-yolo-client:v1.0.0/yolo-app-frontend:v1.1.0
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - name: frontend-port
          containerPort: 80