apiVersion: v1
kind: Service
metadata:
  name: yolo-app-frontend-svc
  namespace: default
spec:
  selector:
    app: yolo-app-frontend
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  type: LoadBalancer