---
# tasks file for roles/docker_install

- name: Check if Docker is already installed
  command: docker --version
  register: docker_check
  ignore_errors: yes

- name: Install Docker only if not present
  apt:
    name: docker.io
    state: present
    update_cache: yes
  when: docker_check.rc != 0
